import { Footer, Header } from "@/components";
import StyledComponentsRegistry from "@/lib/AntdRegistry";
import ReduxProvider from "@/redux/provider";
import theme from "@/theme/themeConfig";
import { ConfigProvider, Layout, Space } from "antd";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Etutor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <StyledComponentsRegistry>
            <ConfigProvider theme={theme}>
              <Space
                direction="vertical"
                style={{ width: "100%" }}
                size={[0, 48]}
              >
                <Layout>
                  <Header />
                  {children}
                  <Footer />
                </Layout>
              </Space>
            </ConfigProvider>
          </StyledComponentsRegistry>
        </ReduxProvider>
      </body>
    </html>
  );
}
